/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttachmentIntelligenceRouteImport } from './routes/attachment-intelligence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmailIntelligenceRouteImport } from './routes/email-intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'
import { Route as UrlIntelligenceRouteImport } from './routes/url-intelligence'
import { Route as VisualIntelligenceRouteImport } from './routes/visual-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentIntelligenceRoute = AttachmentIntelligenceRouteImport.update({
  id: '/attachment-intelligence',
  path: '/attachment-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIntelligenceRoute = EmailIntelligenceRouteImport.update({
  id: '/email-intelligence',
  path: '/email-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlIntelligenceRoute = UrlIntelligenceRouteImport.update({
  id: '/url-intelligence',
  path: '/url-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualIntelligenceRoute = VisualIntelligenceRouteImport.update({
  id: '/visual-intelligence',
  path: '/visual-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attachment-intelligence': typeof AttachmentIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/email-intelligence': typeof EmailIntelligenceRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/url-intelligence': typeof UrlIntelligenceRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attachment-intelligence': typeof AttachmentIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/email-intelligence': typeof EmailIntelligenceRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/url-intelligence': typeof UrlIntelligenceRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attachment-intelligence': typeof AttachmentIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/email-intelligence': typeof EmailIntelligenceRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/url-intelligence': typeof UrlIntelligenceRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attachment-intelligence'
    | '/dashboard'
    | '/email-intelligence'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/threat-intelligence'
    | '/url-intelligence'
    | '/visual-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attachment-intelligence'
    | '/dashboard'
    | '/email-intelligence'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/threat-intelligence'
    | '/url-intelligence'
    | '/visual-intelligence'
  id:
    | '__root__'
    | '/'
    | '/attachment-intelligence'
    | '/dashboard'
    | '/email-intelligence'
    | '/login'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/threat-intelligence'
    | '/url-intelligence'
    | '/visual-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttachmentIntelligenceRoute: typeof AttachmentIntelligenceRoute
  DashboardRoute: typeof DashboardRoute
  EmailIntelligenceRoute: typeof EmailIntelligenceRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
  UrlIntelligenceRoute: typeof UrlIntelligenceRoute
  VisualIntelligenceRoute: typeof VisualIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachment-intelligence': {
      id: '/attachment-intelligence'
      path: '/attachment-intelligence'
      fullPath: '/attachment-intelligence'
      preLoaderRoute: typeof AttachmentIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-intelligence': {
      id: '/email-intelligence'
      path: '/email-intelligence'
      fullPath: '/email-intelligence'
      preLoaderRoute: typeof EmailIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url-intelligence': {
      id: '/url-intelligence'
      path: '/url-intelligence'
      fullPath: '/url-intelligence'
      preLoaderRoute: typeof UrlIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visual-intelligence': {
      id: '/visual-intelligence'
      path: '/visual-intelligence'
      fullPath: '/visual-intelligence'
      preLoaderRoute: typeof VisualIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttachmentIntelligenceRoute: AttachmentIntelligenceRoute,
  DashboardRoute: DashboardRoute,
  EmailIntelligenceRoute: EmailIntelligenceRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
  UrlIntelligenceRoute: UrlIntelligenceRoute,
  VisualIntelligenceRoute: VisualIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
